from turtle import *
t=Turtle() # creating the object of turtle class
s=Screen()

# s.bgcolor("#bc4b08")
#s.bgpic('test.gif')
t.shape('turtle')
s.title("My graphics")
s.setup(400,600)
t.speed(3)
t.pensize(10)
#t.hideturtle()
# t.pencolor('yellow')
# t.fillcolor('red')
t.color("blue","red")
t.write("Mera turtle",font=("Comic Sans Ms",25,"bold"))
t.begin_fill()
t.forward(100)


t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
t.pu()  #t.penup()
t.pensize(1)
t.fd(100)
t.pd()
t.fd(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
t.left(90)
t.fd(100)
# for i in range(4):
#     t.forward(100)
#     t.left(90)
t.backward(200)

t.circle(50)
t.circle(-100)
done()